# Generated by scripts/generate.py from spec/openapi.sdk.json. DO NOT EDIT.

from __future__ import annotations

from decimal import Decimal
from typing import Annotated, Any, Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from cexy._enum import OpenEnum


class ApiScope(OpenEnum):
    """
    Scope attached to an API key.

    Here scopes apply to API keys only, and a session token carries no key scopes at all.
    """

    READ = "read"
    TRADE = "trade"


class BalanceResponse(BaseModel):
    """
    A balance in one asset.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    asset: Annotated[str, Field(description="Asset symbol.")]
    available: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    locked: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    pending: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    total: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]


class CancelAllRequest(BaseModel):
    """
    Cancels every open order, optionally within one market.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    symbol: Annotated[Optional[str], Field(description="Limit the cancellation to one market.")] = None


class CancelAllResponse(BaseModel):
    """
    What a bulk cancellation achieved.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    cancelled: Annotated[List[str], Field(description="Orders cancelled.")]
    failed: Annotated[
        List[str],
        Field(description="Orders that could not be cancelled. Each failure is logged server-side."),
    ]


class CandleInterval(OpenEnum):
    """
    Candle/kline intervals for market data.
    """

    FIELD_1M = "1m"
    FIELD_5M = "5m"
    FIELD_15M = "15m"
    FIELD_30M = "30m"
    FIELD_1H = "1h"
    FIELD_4H = "4h"
    FIELD_1D = "1d"
    FIELD_1W = "1w"


class CandleResponse(BaseModel):
    """
    An OHLCV bucket.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    close: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    high: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    low: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    open: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    open_time: Annotated[AwareDatetime, Field(description="Bucket start.")]
    quote_volume: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    trade_count: Annotated[int, Field(description="Number of trades.", ge=0)]
    volume: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]


class DepositAddressResponse(BaseModel):
    """
    A deposit address.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address: Annotated[str, Field(description="The address to send to.")]
    asset: Annotated[str, Field(description="Asset symbol.")]
    created_at: Annotated[AwareDatetime, Field(description="When the address was issued.")]
    deposit_confirmations: Annotated[int, Field(description="Confirmations before the deposit is credited.", ge=0)]
    memo: Annotated[
        Optional[str],
        Field(
            description="Memo / destination tag. **Required when present** — a deposit without it may be unrecoverable."
        ),
    ] = None
    memo_label: Annotated[Optional[str], Field(description="What to call the memo field in a UI.")] = None
    min_deposit: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    network: Annotated[str, Field(description="Network code.")]


class DepositStatus(OpenEnum):
    """
    Lifecycle of an incoming blockchain deposit.

    One enum makes those unrepresentable.
    """

    DETECTED = "detected"
    CREDITED = "credited"
    REVERSED = "reversed"
    ORPHANED = "orphaned"
    BELOW_MINIMUM = "below_minimum"
    UNDER_REVIEW = "under_review"
    INTERNAL = "internal"


class ErrorCode(OpenEnum):
    """
    PROVISIONAL (errors.yaml) until the served spec includes it.
    """

    VALIDATION_FAILED = "VALIDATION_FAILED"
    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    INVALID_CURSOR = "INVALID_CURSOR"
    PRECISION_EXCEEDED = "PRECISION_EXCEEDED"
    BELOW_MINIMUM = "BELOW_MINIMUM"
    ABOVE_MAXIMUM = "ABOVE_MAXIMUM"
    INVALID_ADDRESS = "INVALID_ADDRESS"
    MEMO_REQUIRED = "MEMO_REQUIRED"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    SESSION_REVOKED = "SESSION_REVOKED"
    TWO_FACTOR_REQUIRED = "TWO_FACTOR_REQUIRED"
    TWO_FACTOR_INVALID = "TWO_FACTOR_INVALID"
    FRESH_TWO_FACTOR_REQUIRED = "FRESH_TWO_FACTOR_REQUIRED"
    FORBIDDEN = "FORBIDDEN"
    API_KEY_NOT_ALLOWED = "API_KEY_NOT_ALLOWED"
    FUTURES_RESTRICTED = "FUTURES_RESTRICTED"
    ACCOUNT_FROZEN = "ACCOUNT_FROZEN"
    ACCOUNT_ON_HOLD = "ACCOUNT_ON_HOLD"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    REGION_BLOCKED = "REGION_BLOCKED"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    INVALID_STATE = "INVALID_STATE"
    IDEMPOTENCY_KEY_CONFLICT = "IDEMPOTENCY_KEY_CONFLICT"
    WINDOW_OPEN = "WINDOW_OPEN"
    EVIDENCE_CONTRADICTS = "EVIDENCE_CONTRADICTS"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    INSUFFICIENT_FEE_FUNDS = "INSUFFICIENT_FEE_FUNDS"
    MARKET_UNAVAILABLE = "MARKET_UNAVAILABLE"
    DEPOSIT_DISABLED = "DEPOSIT_DISABLED"
    WITHDRAWAL_DISABLED = "WITHDRAWAL_DISABLED"
    SELF_TRADE_BLOCKED = "SELF_TRADE_BLOCKED"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL = "INTERNAL"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    ENGINE_OVERLOADED = "ENGINE_OVERLOADED"


class ExitPoolRequest(BaseModel):
    """
    Removes liquidity from a pool.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    shares: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]


class ExitPoolResponse(BaseModel):
    """
    What an exit produced.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    base_returned: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    quote_returned: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    shares_burned: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    shares_held: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]


class FeeScheduleResponse(BaseModel):
    """
    A fee tier.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    label: Annotated[str, Field(description="Human label.")]
    maker_fee_percent: Annotated[Decimal, Field(description="Maker rate, as a percentage.", examples=["0.1"])]
    min_30d_volume_usd: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    taker_fee_percent: Annotated[Decimal, Field(description="Taker rate, as a percentage.", examples=["0.2"])]
    tier: Annotated[int, Field(description="Tier index.", ge=0)]


class JoinPoolRequest(BaseModel):
    """
    Adds liquidity to a pool.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    base_amount: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    max_ratio_deviation_percent: Annotated[
        Optional[Decimal],
        Field(
            description="How far, in percent, the offered ratio may sit from the pool's own before the request is refused rather than repriced. Defaults to 1%.",
            examples=["1"],
        ),
    ] = None
    quote_amount: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]


class JoinPoolResponse(BaseModel):
    """
    What a join produced.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    base_deposited: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    quote_deposited: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    shares_held: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    shares_minted: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]


class LedgerEntryKind(OpenEnum):
    """
    What a ledger entry records.

    Adding a money-moving feature means adding a variant here and emitting entries — never editing a balance formula.
    """

    DEPOSIT = "deposit"
    DEPOSIT_REVERSAL = "deposit_reversal"
    WITHDRAWAL_DEBIT = "withdrawal_debit"
    WITHDRAWAL_FEE = "withdrawal_fee"
    WITHDRAWAL_FEE_RESERVE = "withdrawal_fee_reserve"
    WITHDRAWAL_RELEASE = "withdrawal_release"
    WITHDRAWAL_FEE_RELEASE = "withdrawal_fee_release"
    ORDER_RESERVE = "order_reserve"
    WITHDRAWAL_RESERVE = "withdrawal_reserve"
    ORDER_RELEASE = "order_release"
    TRADE_DEBIT = "trade_debit"
    TRADE_CREDIT = "trade_credit"
    TRADE_FEE = "trade_fee"
    TRANSFER_OUT = "transfer_out"
    TRANSFER_IN = "transfer_in"
    ADJUSTMENT_CREDIT = "adjustment_credit"
    ADJUSTMENT_DEBIT = "adjustment_debit"
    REBATE = "rebate"
    POOL_JOIN = "pool_join"
    POOL_EXIT = "pool_exit"
    FUTURES_TRANSFER_RESERVE = "futures_transfer_reserve"
    FUTURES_TRANSFER_RELEASE = "futures_transfer_release"
    FUTURES_COLLATERAL_SENT = "futures_collateral_sent"
    FUTURES_COLLATERAL_RETURNED = "futures_collateral_returned"
    TRADE_FEE_REVENUE = "trade_fee_revenue"
    WITHDRAWAL_FEE_REVENUE = "withdrawal_fee_revenue"
    FUTURES_TRANSFER_FEE_REVENUE = "futures_transfer_fee_revenue"
    FUTURES_HYPERLIQUID_COST = "futures_hyperliquid_cost"
    FUTURES_TRANSFER_DISCREPANCY = "futures_transfer_discrepancy"
    EXCHANGE_CAPITAL = "exchange_capital"


class LedgerEntryResponse(BaseModel):
    """
    One entry from the account's ledger.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    asset: Annotated[str, Field(description="Asset symbol.")]
    available_after: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    available_delta: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    created_at: Annotated[AwareDatetime, Field(description="When it was applied.")]
    id: Annotated[str, Field(description="Entry id.")]
    kind: LedgerEntryKind
    locked_delta: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    pending_delta: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    reference: Annotated[Any, Field(description="What caused the entry.")]
    sequence: Annotated[int, Field(description="Position in this account's history for this asset.")]


class LiquidityRole(OpenEnum):
    """
    Whether a fill added liquidity (maker) or removed it (taker).
    """

    MAKER = "maker"
    TAKER = "taker"


class MaintenanceReason(OpenEnum):
    """
    Machine-readable reasons a capability is unavailable.
    """

    EXCHANGE_MAINTENANCE = "exchange_maintenance"
    NETWORK_UNAVAILABLE = "network_unavailable"
    DEPOSITS_DISABLED = "deposits_disabled"
    WITHDRAWALS_DISABLED = "withdrawals_disabled"
    ASSET_UNAVAILABLE = "asset_unavailable"


class MaintenanceState(BaseModel):
    """
    Why a capability is currently unavailable.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    message: Annotated[
        Optional[str],
        Field(description="Operator-supplied explanation, when there is one."),
    ] = None
    reason: MaintenanceReason


class MarketStatus(OpenEnum):
    """
    Trading availability of a market.
    """

    ACTIVE = "active"
    PAUSED = "paused"
    SELL_ONLY = "sell_only"
    PRE_TRADING = "pre_trading"
    DELISTED = "delisted"


class NetworkResponse(BaseModel):
    """
    A blockchain network.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    average_block_seconds: Annotated[
        int,
        Field(
            description="Typical seconds between blocks, for estimating confirmation time.",
            ge=0,
        ),
    ]
    code: Annotated[str, Field(description="Stable code.", examples=["bitcoin-mainnet"])]
    deposits_operational: Annotated[
        bool,
        Field(
            description="Whether deposits on this network are actually being detected.\n\nFalse means either half of the pipeline is down: the last scan pass failed — a refused block range, a rate limit, a node that answers but will not serve logs — or finality could not be established, so deposits are being held rather than credited.\n\nDeposits sent now will be credited late, whenever the chain recovers, rather than lost. This is the field a status page should use to say deposits are degraded; `reachable` only says the node replies, which it may well do while yielding nothing."
        ),
    ]
    explorer_address_url_template: Annotated[
        Optional[str],
        Field(description="Template for an address explorer link. `{address}` is substituted."),
    ] = None
    explorer_tx_url_template: Annotated[
        Optional[str],
        Field(
            description="Template for a transaction explorer link. `{txid}` is substituted.\n\nAbsent when the operator has configured none; render no link rather than guessing a URL."
        ),
    ] = None
    is_active: Annotated[bool, Field(description="Whether the network is operational.")]
    name: Annotated[str, Field(description="Display name.")]
    reachable: Annotated[
        bool,
        Field(
            description='Whether the node answers at all.\n\nNarrower than it sounds, and deliberately so: a reachable node can still be failing to yield deposits. Do not render this alone as "network up".'
        ),
    ]


class NotificationKind(OpenEnum):
    """
    What a notice is about.

    A closed enum so a client can render each kind deliberately — an icon, a colour, a link — rather than pattern-matching on prose that may be reworded.
    """

    DEPOSIT_DETECTED = "deposit_detected"
    DEPOSIT_CREDITED = "deposit_credited"
    WITHDRAWAL_REQUESTED = "withdrawal_requested"
    WITHDRAWAL_SENT = "withdrawal_sent"
    WITHDRAWAL_COMPLETED = "withdrawal_completed"
    WITHDRAWAL_FAILED = "withdrawal_failed"
    ORDER_FILLED = "order_filled"
    SECURITY = "security"
    LISTING_DECISION = "listing_decision"
    ANNOUNCEMENT = "announcement"


class NotificationResponse(BaseModel):
    """
    An in-app notice.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    body: Annotated[str, Field(description="One or two sentences.")]
    created_at: Annotated[AwareDatetime, Field(description="When it was created.")]
    id: Annotated[str, Field(description="Notice id.")]
    kind: NotificationKind
    read: Annotated[bool, Field(description="Whether it has been read.")]
    resource_id: Annotated[
        Optional[str],
        Field(description="The referenced resource's opaque id, for linking."),
    ] = None
    resource_type: Annotated[
        Optional[str],
        Field(description="What it refers to: `deposit`, `withdrawal`, `order`."),
    ] = None
    title: Annotated[str, Field(description="Short heading.")]


class OrderBookResponse(BaseModel):
    """
    One side of the order book, aggregated by price.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    asks: Annotated[List[List[Decimal]], Field(description="Asks, best first.")]
    bids: Annotated[
        List[List[Decimal]],
        Field(description="Bids, best first, as `[price, quantity]` pairs."),
    ]
    sequence: Annotated[
        int,
        Field(
            description="The realtime sequence this snapshot is current as of.\n\nTo synchronise with the `orderbook:{symbol}` WebSocket channel: subscribe first, fetch this snapshot, and ignore updates whose `sequence` is at or below this value. Every update carries the complete top 50 levels of both sides and replaces the previous state (there are no deltas). A gap in `sequence` only means the book was briefly stale; the next update is complete.",
            ge=0,
        ),
    ]
    symbol: Annotated[str, Field(description="Market symbol.")]
    timestamp: Annotated[AwareDatetime, Field(description="When this snapshot was taken.")]


class OrderSide(OpenEnum):
    """
    Which side of a market an order takes.
    """

    BUY = "buy"
    SELL = "sell"


class OrderStatus(OpenEnum):
    """
    Lifecycle of an order.
    """

    PENDING = "pending"
    OPEN = "open"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    PENDING_TRIGGER = "pending_trigger"
    EXPIRED = "expired"


class OrderType(OpenEnum):
    """
    Order types the matching engine accepts.

    That separation is kept: this enum covers what the book itself understands.
    """

    LIMIT = "limit"
    MARKET = "market"
    STOP_LIMIT = "stop_limit"
    STOP_MARKET = "stop_market"


class PasswordRules(BaseModel):
    """
    Password constraints, published so a form can validate locally.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    allows_email_substring: Annotated[
        bool,
        Field(description="Whether the password may contain the account's email address."),
    ]
    description: Annotated[
        str,
        Field(description="A short description of any further rules, for display beside the input."),
    ]
    max_length: Annotated[int, Field(description="Maximum length in characters.", ge=0)]
    min_length: Annotated[int, Field(description="Minimum length in characters.", ge=0)]


class PoolStatus(OpenEnum):
    """
    Whether a pool quotes, and whether it accepts new liquidity.
    """

    ACTIVE = "active"
    PAUSED = "paused"
    CLOSING = "closing"


class PublicTradeResponse(BaseModel):
    """
    A public trade.

    Deliberately anonymous: no account identifiers, and no indication of which side was the resting order beyond the aggressor direction.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: Annotated[str, Field(description="Trade id.")]
    price: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    quantity: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    sequence: Annotated[int, Field(description="Gapless per-market sequence.")]
    side: OrderSide
    timestamp: Annotated[AwareDatetime, Field(description="When it executed.")]


class ServerTimeResponse(BaseModel):
    """
    The server's clock.

    Two-factor codes are time-based, so a client can compare its own clock against this before a skewed clock gets a correct code rejected.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    epoch_ms: Annotated[int, Field(description="Current time in milliseconds since the Unix epoch.")]
    iso: Annotated[
        str,
        Field(
            description="Current time as RFC 3339 with an explicit UTC offset.",
            examples=["2024-05-01T12:34:56.789+00:00"],
        ),
    ]


class SortDirection(OpenEnum):
    """
    Sort direction for a paginated listing.
    """

    ASC = "asc"
    DESC = "desc"


class SubAccountResponse(BaseModel):
    """
    A sub-account.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    can_withdraw: Annotated[
        bool,
        Field(
            description="Always `false`. A sub-account has no withdrawal path — stated explicitly so a client does not have to infer it."
        ),
    ]
    created_at: Annotated[AwareDatetime, Field(description="When it was created.")]
    id: Annotated[
        str,
        Field(description="Opaque identifier. Use it to transfer funds and to issue API keys."),
    ]
    is_active: Annotated[bool, Field(description="Whether it may trade.")]
    label: Annotated[str, Field(description="The label given at creation.")]


class TimeInForce(OpenEnum):
    """
    How long an order remains eligible to match.
    """

    GTC = "gtc"
    IOC = "ioc"
    FOK = "fok"
    POST_ONLY = "post_only"


class TriggerDirection(OpenEnum):
    """
    Which way the price must move for a stop to fire.

    Explicit rather than inferred from the side, because the inference is ambiguous: a sell stop below the market is a stop-loss, and a sell stop above it is a take-profit. Both are legitimate, and guessing wrong means an order that fires at exactly the wrong moment — which is the one thing a protective order must never do.
    """

    ABOVE = "above"
    BELOW = "below"


class WithdrawalAddressResponse(BaseModel):
    """
    A saved withdrawal address.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address: Annotated[str, Field(description="The address.")]
    asset: Annotated[Optional[str], Field(description="Asset, when restricted to one.")] = None
    created_at: Annotated[AwareDatetime, Field(description="When it was saved.")]
    id: Annotated[str, Field(description="Address-book entry id.")]
    label: Annotated[str, Field(description="Your label.")]
    last_used_at: Annotated[Optional[AwareDatetime], Field(description="When it was last withdrawn to.")] = None
    memo: Annotated[Optional[str], Field(description="Memo, if any.")] = None
    network: Annotated[str, Field(description="Network code.")]
    verified: Annotated[bool, Field(description="Whether ownership has been confirmed.")]


class WithdrawalStatus(OpenEnum):
    """
    Lifecycle of an outgoing withdrawal.
    """

    REQUESTED = "requested"
    PENDING_APPROVAL = "pending_approval"
    APPROVED = "approved"
    PROCESSING = "processing"
    BROADCAST = "broadcast"
    COMPLETED = "completed"
    REJECTED = "rejected"
    CANCELLED = "cancelled"
    FAILED = "failed"
    BROADCAST_UNKNOWN = "broadcast_unknown"


class ApiKeyResponse(BaseModel):
    """
    An existing key. Never carries the secret.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    allowed_ips: Annotated[
        List[str],
        Field(description="Permitted source addresses. Empty means unrestricted."),
    ]
    created_at: Annotated[AwareDatetime, Field(description="When it was created.")]
    expires_at: Annotated[Optional[AwareDatetime], Field(description="When it stops working.")] = None
    id: Annotated[str, Field(description="Opaque key identifier, used to revoke it.")]
    key_id: Annotated[str, Field(description="The public key id, sent as `X-API-Key`.")]
    label: Annotated[str, Field(description="Human label.")]
    last_used_at: Annotated[Optional[AwareDatetime], Field(description="When it was last used, if ever.")] = None
    revoked: Annotated[bool, Field(description="Whether it has been revoked.")]
    scopes: Annotated[List[ApiScope], Field(description="Granted scopes.")]


class AssetNetworkResponse(BaseModel):
    """
    An asset's policy on one network.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    contract_address: Annotated[
        Optional[str],
        Field(description="Contract address or chain asset id, for a token."),
    ] = None
    deposit_confirmations: Annotated[int, Field(description="Confirmations before a deposit is credited.", ge=0)]
    deposit_enabled: Annotated[bool, Field(description="Whether deposits are accepted.")]
    maintenance: Optional[MaintenanceState] = None
    max_withdrawal: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    memo_label: Annotated[Optional[str], Field(description="What to call the memo field in a UI.")] = None
    memo_required: Annotated[bool, Field(description="Whether a memo is mandatory.")]
    memo_supported: Annotated[bool, Field(description="Whether the network uses a memo / destination tag.")]
    min_deposit: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    min_withdrawal: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    network: Annotated[str, Field(description="Network code.", examples=["bitcoin-mainnet"])]
    network_name: Annotated[str, Field(description="Network display name.")]
    notice: Annotated[Optional[str], Field(description="Operator note.")] = None
    token_kind: Annotated[str, Field(description="How the asset exists on this chain.")]
    withdrawal_decimals: Annotated[
        int,
        Field(description="Decimal places a withdrawal amount is truncated to.", ge=0),
    ]
    withdrawal_enabled: Annotated[bool, Field(description="Whether withdrawals are accepted.")]
    withdrawal_fee: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    withdrawal_fee_asset: Annotated[str, Field(description="Asset the withdrawal fee is charged in.")]


class AssetResponse(BaseModel):
    """
    A tradable asset.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    decimals: Annotated[
        int,
        Field(
            description="Accounting precision: the decimal places the exchange records internally.\n\nUse this for arithmetic. For rendering, use `display_decimals`.",
            ge=0,
        ),
    ]
    display_decimals: Annotated[
        int,
        Field(
            description="Decimal places to show in a user interface.\n\nAlways less than or equal to `decimals`. Rounding for display is presentation only and must never be fed back into a request.",
            ge=0,
        ),
    ]
    icon_key: Annotated[
        Optional[str],
        Field(description="Identifier for a client-bundled icon, when no logo URL is set."),
    ] = None
    logo_url: Annotated[
        Optional[str],
        Field(description="Logo URL, when the operator has configured one."),
    ] = None
    max_price_age_secs: Annotated[
        int,
        Field(
            description="How old this asset's price may be before it is refused, in seconds.\n\nThe global default unless an operator set an override for this asset. Exposed beside the flag because the flag alone cannot explain itself: an asset that is not stale after a week and one that is not stale after an hour look identical without it.",
            ge=0,
        ),
    ]
    name: Annotated[str, Field(description="Display name.")]
    networks: Annotated[
        List[AssetNetworkResponse],
        Field(description="Networks this asset can be deposited to or withdrawn from."),
    ]
    notice: Annotated[Optional[str], Field(description="Operator note, e.g. why deposits are paused.")] = None
    symbol: Annotated[str, Field(description="Uppercase ticker.", examples=["BTC"])]
    trading_enabled: Annotated[bool, Field(description="Whether the asset may appear in markets.")]
    usd_price: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    usd_price_stale: Annotated[
        bool,
        Field(
            description="Whether that price is too old to compute with.\n\nWhen true, the exchange refuses to derive anything from it: daily limits and auto-approval fail closed rather than guess, and a stored USD value is recorded as absent rather than as a confident wrong figure."
        ),
    ]
    usd_price_updated_at: Annotated[
        AwareDatetime,
        Field(
            description="When that price was last set.\n\nExposed because the price is typed in by an operator and refreshed by nothing — there is no feed. Without the timestamp a caller cannot tell a price set an hour ago from one set last month, and both look equally authoritative."
        ),
    ]
    website_url: Annotated[Optional[str], Field(description="Project website.")] = None


class DepositResponse(BaseModel):
    """
    A deposit.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address: Annotated[str, Field(description="Address that received it.")]
    amount: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    asset: Annotated[str, Field(description="Asset symbol.")]
    confirmations: Annotated[int, Field(description="Confirmations observed.", ge=0)]
    credited_at: Annotated[Optional[AwareDatetime], Field(description="When it was credited.")] = None
    explorer_url: Annotated[
        Optional[str],
        Field(description="Explorer link, when the network has one configured."),
    ] = None
    first_seen_at: Annotated[AwareDatetime, Field(description="When it was first observed.")]
    id: Annotated[str, Field(description="Deposit id.")]
    memo: Annotated[Optional[str], Field(description="Memo, if any.")] = None
    network: Annotated[str, Field(description="Network code.")]
    note: Annotated[Optional[str], Field(description="Operator note, e.g. why it was reversed.")] = None
    output_index: Annotated[
        int,
        Field(
            description="Position within the transaction. Distinguishes two outputs of one transaction.",
            ge=0,
        ),
    ]
    required_confirmations: Annotated[int, Field(description="Confirmations required to credit.", ge=0)]
    status: DepositStatus
    txid: Annotated[str, Field(description="Transaction hash.")]


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: ErrorCode
    message: Annotated[str, Field(description="Human-readable; may change. Branch on `code`.")]
    details: Optional[Dict[str, Any]] = None
    fields: Optional[Dict[str, str]] = None
    request_id: Optional[str] = None
    retryable: bool


class ErrorResponse(BaseModel):
    """
    The error envelope returned by every failing request.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    error: ErrorBody


class ExchangeConfigResponse(BaseModel):
    """
    Public exchange configuration.

    Everything a frontend needs to render itself without a deploy: branding, limits, supported intervals, and whether the exchange is in maintenance.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    candle_intervals: Annotated[List[CandleInterval], Field(description="Candle intervals the API serves.")]
    default_page_size: Annotated[int, Field(description="Default page size for paginated endpoints.", ge=0)]
    email_verification_required: Annotated[
        bool,
        Field(
            description="Whether registration verifies the email address with an emailed code before the authenticator step. Lets a signup form show the right number of steps up front."
        ),
    ]
    features: Annotated[
        Dict[str, bool],
        Field(
            description="Feature flags a frontend may use to hide unavailable functionality.\n\nPresentation only. The backend enforces every rule independently."
        ),
    ]
    maintenance_message: Annotated[Optional[str], Field(description="Message to show while in maintenance.")] = None
    maintenance_mode: Annotated[bool, Field(description="Whether the exchange is in maintenance mode.")]
    max_page_size: Annotated[int, Field(description="Maximum page size.", ge=0)]
    name: Annotated[str, Field(description="Display name.")]
    password_rules: PasswordRules
    registration_enabled: Annotated[bool, Field(description="Whether new registrations are accepted.")]
    support_url: Annotated[Optional[str], Field(description="Support contact.")] = None
    two_factor_freshness_seconds: Annotated[
        int,
        Field(
            description="Seconds a verified two-factor code authorises sensitive actions for.",
            ge=0,
        ),
    ]
    websocket_path: Annotated[
        str,
        Field(description="Where to open the realtime connection, relative to this API's origin."),
    ]
    websocket_protocol_version: Annotated[
        int,
        Field(description="The realtime protocol version this server speaks.", ge=0),
    ]


class FillResponse(BaseModel):
    """
    One of the caller's executions.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    fee: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    fee_asset: Annotated[str, Field(description="Asset the fee was charged in.")]
    order_id: Annotated[str, Field(description="The caller's order.")]
    price: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    quantity: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    quote_quantity: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    role: LiquidityRole
    side: OrderSide
    symbol: Annotated[str, Field(description="Market symbol.")]
    timestamp: Annotated[AwareDatetime, Field(description="When it executed.")]
    trade_id: Annotated[str, Field(description="Trade id.")]


class MarketResponse(BaseModel):
    """
    A tradable market and its current ticker.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    base_asset: Annotated[str, Field(description="Base asset symbol.")]
    best_ask: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    best_bid: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    change_24h_percent: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    high_24h: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    last_price: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    last_trade_at: Annotated[Optional[AwareDatetime], Field(description="Time of the most recent trade.")] = None
    lot_size: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    low_24h: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    max_quantity: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    min_notional: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    min_quantity: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    price_decimals: Annotated[int, Field(description="Decimal places a price may carry.", ge=0)]
    quantity_decimals: Annotated[int, Field(description="Decimal places a quantity may carry.", ge=0)]
    quote_asset: Annotated[str, Field(description="Quote asset symbol.")]
    quote_volume_24h: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    status: MarketStatus
    supported_order_types: Annotated[List[OrderType], Field(description="Order types this market accepts.")]
    supported_time_in_force: Annotated[
        List[TimeInForce],
        Field(description="Time-in-force options this market accepts."),
    ]
    symbol: Annotated[str, Field(description="`BASE/QUOTE`.", examples=["BTC/USDT"])]
    tick_size: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    trading_starts_at: Annotated[
        Optional[AwareDatetime],
        Field(description="When trading opens, for a market not yet live."),
    ] = None
    volume_24h: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]


class OrderResponse(BaseModel):
    """
    An order.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    average_price: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    client_order_id: Annotated[Optional[str], Field(description="Your identifier, if you supplied one.")] = None
    closed_at: Annotated[Optional[AwareDatetime], Field(description="When it reached a terminal state.")] = None
    created_at: Annotated[AwareDatetime, Field(description="When it was placed.")]
    fee_asset: Annotated[Optional[str], Field(description="Asset the fees were charged in.")] = None
    fee_paid: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    filled_quantity: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    filled_quote_quantity: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    id: Annotated[str, Field(description="Order id.")]
    price: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    quantity: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    quote_quantity: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    remaining_quantity: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    reserved_remaining: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    side: OrderSide
    status: OrderStatus
    status_reason: Annotated[Optional[str], Field(description="Why the order was rejected or cancelled.")] = None
    stop_price: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    symbol: Annotated[str, Field(description="Market symbol.")]
    time_in_force: TimeInForce
    trigger_direction: Optional[TriggerDirection] = None
    triggered_at: Annotated[Optional[AwareDatetime], Field(description="When the trigger fired, if it has.")] = None
    type: OrderType
    updated_at: Annotated[AwareDatetime, Field(description="When it last changed.")]


class PlaceOrderRequest(BaseModel):
    """
    Places an order.

    Set `client_order_id` to make a retry safe: it is unique per account, a repeated id is refused before any funds move, and the order can be recovered with GET /api/v1/trading/orders/by-client-id/{client_order_id}. `Idempotency-Key` has no effect on this endpoint.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    client_order_id: Annotated[Optional[str], Field(description="Your own identifier. Unique per account.")] = None
    price: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    quantity: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    quote_quantity: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    side: OrderSide
    stop_price: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    symbol: Annotated[str, Field(description="Market symbol.", examples=["BTC/USDT"])]
    time_in_force: Optional[TimeInForce] = None
    trigger_direction: Optional[TriggerDirection] = None
    type: OrderType


class PlaceOrderResponse(BaseModel):
    """
    The result of placing an order, including anything it executed immediately.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    fills: Annotated[List[FillResponse], Field(description="Fills produced on entry, oldest first.")]
    order: OrderResponse


class PoolResponse(BaseModel):
    """
    A pool as a client sees it.

    Reserves are the custody account's balances, so they include liquidity currently locked in resting orders. `price` is the curve's mid, which sits between the pool's own best bid and ask by exactly its fee — it is not a traded price.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    base_reserve: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    created_at: Annotated[AwareDatetime, Field(description="When the pool was created.")]
    fee_percent: Annotated[
        Decimal,
        Field(
            description="The pool's fee, in percent, priced into every quote it rests.",
            examples=["0.3"],
        ),
    ]
    id: Annotated[str, Field(description="Identifier.")]
    ladder_steps: Annotated[int, Field(description="Ladder steps per side.", ge=0)]
    price: Annotated[
        Optional[Decimal],
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ] = None
    quote_reserve: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    shares_outstanding: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    status: PoolStatus
    symbol: Annotated[str, Field(description="Market the pool quotes.")]


class WithdrawalHistoryEntry(BaseModel):
    """
    One transition in a withdrawal's life.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    at: Annotated[AwareDatetime, Field(description="When.")]
    reason: Annotated[Optional[str], Field(description="Why, where a reason applies.")] = None
    status: WithdrawalStatus


class WithdrawalResponse(BaseModel):
    """
    A withdrawal.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address: Annotated[str, Field(description="Destination.")]
    amount: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    asset: Annotated[str, Field(description="Asset symbol.")]
    broadcast_at: Annotated[Optional[AwareDatetime], Field(description="When it was broadcast.")] = None
    cancellable: Annotated[bool, Field(description="Whether the account holder may still cancel it.")]
    completed_at: Annotated[
        Optional[AwareDatetime],
        Field(description="When it confirmed to the required depth."),
    ] = None
    confirmations: Annotated[int, Field(description="Confirmations observed.", ge=0)]
    created_at: Annotated[AwareDatetime, Field(description="When it was requested.")]
    explorer_url: Annotated[Optional[str], Field(description="Explorer link, when available.")] = None
    fee: Annotated[
        Decimal,
        Field(
            description='Exact decimal amount, serialized as a string to avoid floating-point precision loss. Example: "1.50000000".'
        ),
    ]
    fee_asset: Annotated[str, Field(description="Asset the fee was charged in.")]
    history: Annotated[
        List[WithdrawalHistoryEntry],
        Field(description="Transitions this withdrawal has been through."),
    ]
    id: Annotated[str, Field(description="Withdrawal id.")]
    memo: Annotated[Optional[str], Field(description="Memo, if any.")] = None
    network: Annotated[str, Field(description="Network code.")]
    status: WithdrawalStatus
    txid: Annotated[Optional[str], Field(description="Transaction hash, once broadcast.")] = None
