# Generated by scripts/generate.py from spec/openapi.sdk.json. DO NOT EDIT.
from __future__ import annotations

from typing import NamedTuple, Tuple


class Operation(NamedTuple):
    operation_id: str
    method: str
    path: str
    auth: str  # "none" | "api_key"
    scope: str  # "-" | "read" | "trade"
    path_params: Tuple[str, ...]
    query_params: Tuple[str, ...]
    idempotency_header: bool


OPERATIONS = {
    "list_api_keys": Operation("list_api_keys", "GET", "/api/v1/account/api-keys", "api_key", "read", (), (), False),
    "list_balances": Operation("list_balances", "GET", "/api/v1/account/balances", "api_key", "read", (), (), False),
    "get_balance": Operation(
        "get_balance", "GET", "/api/v1/account/balances/{asset}", "api_key", "read", ("asset",), (), False
    ),
    "get_ledger": Operation(
        "get_ledger",
        "GET",
        "/api/v1/account/ledger",
        "api_key",
        "read",
        (),
        ("asset", "cursor", "limit", "direction"),
        False,
    ),
    "list_notifications": Operation(
        "list_notifications",
        "GET",
        "/api/v1/account/notifications",
        "api_key",
        "read",
        (),
        ("unread_only", "cursor", "limit", "direction"),
        False,
    ),
    "list_sub_accounts": Operation(
        "list_sub_accounts", "GET", "/api/v1/account/sub-accounts", "api_key", "read", (), (), False
    ),
    "sub_account_balances": Operation(
        "sub_account_balances",
        "GET",
        "/api/v1/account/sub-accounts/{id}/balances",
        "api_key",
        "read",
        ("id",),
        (),
        False,
    ),
    "list_assets": Operation("list_assets", "GET", "/api/v1/assets", "none", "-", (), (), False),
    "get_asset": Operation("get_asset", "GET", "/api/v1/assets/{symbol}", "none", "-", ("symbol",), (), False),
    "exchange_config": Operation("exchange_config", "GET", "/api/v1/config", "none", "-", (), (), False),
    "export_deposits": Operation(
        "export_deposits", "GET", "/api/v1/exports/deposits", "api_key", "read", (), ("from", "to"), False
    ),
    "export_ledger": Operation(
        "export_ledger", "GET", "/api/v1/exports/ledger", "api_key", "read", (), ("from", "to"), False
    ),
    "export_orders": Operation(
        "export_orders", "GET", "/api/v1/exports/orders", "api_key", "read", (), ("from", "to"), False
    ),
    "export_trades": Operation(
        "export_trades", "GET", "/api/v1/exports/trades", "api_key", "read", (), ("from", "to"), False
    ),
    "export_withdrawals": Operation(
        "export_withdrawals", "GET", "/api/v1/exports/withdrawals", "api_key", "read", (), ("from", "to"), False
    ),
    "list_fee_schedules": Operation("list_fee_schedules", "GET", "/api/v1/fees", "none", "-", (), (), False),
    "list_markets": Operation("list_markets", "GET", "/api/v1/markets", "none", "-", (), (), False),
    "get_market": Operation("get_market", "GET", "/api/v1/markets/{symbol}", "none", "-", ("symbol",), (), False),
    "get_candles": Operation(
        "get_candles",
        "GET",
        "/api/v1/markets/{symbol}/candles",
        "none",
        "-",
        ("symbol",),
        ("interval", "start_time", "end_time", "limit"),
        False,
    ),
    "get_order_book": Operation(
        "get_order_book", "GET", "/api/v1/markets/{symbol}/orderbook", "none", "-", ("symbol",), ("depth",), False
    ),
    "get_market_trades": Operation(
        "get_market_trades",
        "GET",
        "/api/v1/markets/{symbol}/trades",
        "none",
        "-",
        ("symbol",),
        ("cursor", "limit", "direction"),
        False,
    ),
    "list_networks": Operation("list_networks", "GET", "/api/v1/networks", "none", "-", (), (), False),
    "list_pools": Operation("list_pools", "GET", "/api/v1/pools", "none", "-", (), (), False),
    "get_pool": Operation("get_pool", "GET", "/api/v1/pools/{symbol}", "none", "-", ("symbol",), (), False),
    "exit_pool": Operation(
        "exit_pool", "POST", "/api/v1/pools/{symbol}/exit", "api_key", "trade", ("symbol",), (), True
    ),
    "join_pool": Operation(
        "join_pool", "POST", "/api/v1/pools/{symbol}/join", "api_key", "trade", ("symbol",), (), True
    ),
    "server_time": Operation("server_time", "GET", "/api/v1/time", "none", "-", (), (), False),
    "list_open_orders": Operation(
        "list_open_orders", "GET", "/api/v1/trading/orders", "api_key", "read", (), ("symbol", "status"), False
    ),
    "place_order": Operation("place_order", "POST", "/api/v1/trading/orders", "api_key", "trade", (), (), False),
    "get_order_by_client_id": Operation(
        "get_order_by_client_id",
        "GET",
        "/api/v1/trading/orders/by-client-id/{client_order_id}",
        "api_key",
        "read",
        ("client_order_id",),
        (),
        False,
    ),
    "cancel_all": Operation(
        "cancel_all", "POST", "/api/v1/trading/orders/cancel-all", "api_key", "trade", (), (), False
    ),
    "order_history": Operation(
        "order_history",
        "GET",
        "/api/v1/trading/orders/history",
        "api_key",
        "read",
        (),
        ("symbol", "status", "cursor", "limit", "direction"),
        False,
    ),
    "cancel_order": Operation(
        "cancel_order", "DELETE", "/api/v1/trading/orders/{order_id}", "api_key", "trade", ("order_id",), (), False
    ),
    "get_order": Operation(
        "get_order", "GET", "/api/v1/trading/orders/{order_id}", "api_key", "read", ("order_id",), (), False
    ),
    "trade_history": Operation(
        "trade_history",
        "GET",
        "/api/v1/trading/trades",
        "api_key",
        "read",
        (),
        ("symbol", "cursor", "limit", "direction"),
        False,
    ),
    "deposit_address": Operation(
        "deposit_address", "GET", "/api/v1/wallet/deposit-address", "api_key", "read", (), ("asset", "network"), False
    ),
    "list_deposits": Operation(
        "list_deposits",
        "GET",
        "/api/v1/wallet/deposits",
        "api_key",
        "read",
        (),
        ("asset", "cursor", "limit", "direction"),
        False,
    ),
    "get_deposit": Operation(
        "get_deposit", "GET", "/api/v1/wallet/deposits/{deposit_id}", "api_key", "read", ("deposit_id",), (), False
    ),
    "list_withdrawal_addresses": Operation(
        "list_withdrawal_addresses", "GET", "/api/v1/wallet/withdrawal-addresses", "api_key", "read", (), (), False
    ),
    "list_withdrawals": Operation(
        "list_withdrawals",
        "GET",
        "/api/v1/wallet/withdrawals",
        "api_key",
        "read",
        (),
        ("asset", "cursor", "limit", "direction"),
        False,
    ),
    "get_withdrawal": Operation(
        "get_withdrawal",
        "GET",
        "/api/v1/wallet/withdrawals/{withdrawal_id}",
        "api_key",
        "read",
        ("withdrawal_id",),
        (),
        False,
    ),
}
