# Generated by scripts/unasync.py from cexy/_async/client.py. DO NOT EDIT.
"""The synchronous client (``Client``).

Synchronous version, generated from ``cexy/_async/client.py`` by ``scripts/unasync.py``:
edit that file, not this one.
"""

from __future__ import annotations

from types import TracebackType
from typing import Optional, Type

import httpx

from cexy._common import (
    DEFAULT_BASE_URL,
    DEFAULT_RATE_LIMIT_ANONYMOUS,
    DEFAULT_RATE_LIMIT_WITH_KEY,
    user_agent,
    validate_base_url,
)
from cexy._generated import models as m
from cexy._opmap import operation
from cexy._sync.resources import (
    Account,
    Assets,
    Exports,
    Fees,
    Markets,
    Networks,
    Pools,
    Trading,
    Wallet,
)
from cexy._sync.transport import SyncTransport
from cexy.auth import REDACTED, Authenticator, build_authenticator
from cexy.errors import ConfigurationError


class Client:
    """CEXY.io REST client (synchronous).

    Public market data needs no credentials. For account and trading endpoints pass an
    API key pair; both values are required together. Keys are sent only on endpoints that
    need them, only as ``X-API-Key``/``X-API-Secret`` headers, and are redacted from
    ``repr``, logs and exceptions.

    The client-side rate limiter defaults to 100 requests/minute without a key and 300 with
    one (``rate_limit_per_minute`` overrides it); it adapts to ``X-RateLimit-*`` headers.

    ``base_url`` must be ``https://``. ``allow_insecure=True`` permits ``http://`` for a
    loopback host only (local testing).

    Use as ``with Client() as client: ...`` or call ``client.close()``.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        base_url: str = DEFAULT_BASE_URL,
        timeout: float = 10,
        max_retries: int = 3,
        user_agent_suffix: Optional[str] = None,
        *,
        rate_limit_per_minute: Optional[float] = None,
        authenticator: Optional[Authenticator] = None,
        http_client: Optional[httpx.Client] = None,
        allow_insecure: bool = False,
        auth: str = "headers",
    ) -> None:
        """``auth``: how ``api_key``/``api_secret`` authenticate. ``"headers"`` (default): the
        ``X-API-Key`` and ``X-API-Secret`` headers. ``"hmac"``: request signing (accepted by the
        API since 2026-10-01); the secret never leaves the process, and a key issued before
        signing existed fails with ``KEY_NOT_SIGNABLE`` (no fallback)."""
        mode = auth
        auth_obj: Optional[Authenticator]
        try:
            auth_obj = build_authenticator(api_key, api_secret, mode)
        except ValueError as exc:
            raise ConfigurationError(str(exc)) from None
        if authenticator is not None:
            if auth_obj is not None:
                raise ConfigurationError("pass either api_key/api_secret or authenticator, not both")
            if not isinstance(authenticator, Authenticator):
                raise ConfigurationError("authenticator must implement cexy.auth.Authenticator")
            auth_obj = authenticator
        self._auth = auth_obj
        if rate_limit_per_minute is None:
            # Server limits: ~120/min per IP for anonymous requests, ~600/min per key.
            rate_limit_per_minute = (
                DEFAULT_RATE_LIMIT_WITH_KEY if auth_obj is not None else DEFAULT_RATE_LIMIT_ANONYMOUS
            )
        self._transport = SyncTransport(
            base_url=validate_base_url(base_url, allow_insecure),
            auth=auth_obj,
            timeout=timeout,
            max_retries=max_retries,
            user_agent=user_agent(user_agent_suffix),
            rate_limit_per_minute=rate_limit_per_minute,
            http_client=http_client,
        )
        self.markets = Markets(self._transport)
        self.assets = Assets(self._transport)
        self.networks = Networks(self._transport)
        self.fees = Fees(self._transport)
        self.pools = Pools(self._transport)
        self.account = Account(self._transport)
        self.exports = Exports(self._transport)
        self.wallet = Wallet(self._transport)
        self.trading = Trading(self._transport)

    @property
    def base_url(self) -> str:
        return self._transport.base_url

    @property
    def has_credentials(self) -> bool:
        return self._auth is not None

    @operation("server_time")
    def time(self) -> m.ServerTimeResponse:
        """The server clock (public)."""
        payload = self._transport.request("server_time")
        return m.ServerTimeResponse.model_validate(payload["data"])

    @operation("exchange_config")
    def config(self) -> m.ExchangeConfigResponse:
        """Public exchange configuration: maintenance mode, page sizes, intervals (public)."""
        payload = self._transport.request("exchange_config")
        return m.ExchangeConfigResponse.model_validate(payload["data"])

    def close(self) -> None:
        self._transport.close()

    def __enter__(self) -> Client:
        return self

    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> None:
        self.close()

    def __repr__(self) -> str:
        auth = REDACTED if self._auth is not None else None
        return f"{type(self).__name__}(base_url={self.base_url!r}, credentials={auth!r})"

    __str__ = __repr__

    def __reduce__(self) -> str:
        raise TypeError(f"{type(self).__name__} cannot be pickled (it may hold a secret)")
