# Generated by scripts/unasync.py from cexy/_async/pagination.py. DO NOT EDIT.
"""Cursor pagination: ``items`` + ``next_cursor`` + ``has_more``.

Synchronous version, generated from ``cexy/_async/pagination.py`` by ``scripts/unasync.py``:
edit that file, not this one.
"""

from __future__ import annotations

from typing import Any, Callable, Generic, Iterator, List, Optional, Type, TypeVar

from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)


class Page(Generic[T]):
    """One page of results.

    ``for item in page.auto_paging_iter()`` walks this page and every later one,
    fetching lazily. ``page.next_page()`` fetches just the next page.
    """

    def __init__(
        self,
        items: List[T],
        next_cursor: Optional[str],
        has_more: bool,
        fetch: Callable[[str], Any],
    ) -> None:
        self.items = items
        self.next_cursor = next_cursor
        self.has_more = has_more
        self._fetch = fetch

    @classmethod
    def parse(cls, payload: Any, model: Type[T], fetch: Callable[[str], Any]) -> Page[T]:
        items = [model.model_validate(x) for x in payload.get("items", [])]
        cursor = payload.get("next_cursor")
        has_more = bool(payload.get("has_more", False)) and bool(cursor)
        return cls(items, cursor, has_more, fetch)

    def next_page(self) -> Optional[Page[T]]:
        if not self.has_more or not self.next_cursor:
            return None
        page: Page[T] = self._fetch(self.next_cursor)
        return page

    def auto_paging_iter(self) -> Iterator[T]:
        page: Optional[Page[T]] = self
        while page is not None:
            yield from page.items
            page = page.next_page()

    def __len__(self) -> int:
        return len(self.items)

    def __repr__(self) -> str:
        return f"{type(self).__name__}(items={len(self.items)}, has_more={self.has_more})"
