#!/usr/bin/env python3
"""Regenerate cexy/_generated/ from spec/openapi.sdk.json.

Steps:
1. Pre-process the spec: every decimal string (the ``Amount`` schema and string
   ``*_percent`` fields) becomes ``format: decimal`` so the generator emits ``Decimal``.
2. Run datamodel-code-generator (pinned in pyproject ``[dev]``) into ``models.py``.
3. Post-process: response enums inherit ``cexy._enum.OpenEnum`` so unknown values
   parse instead of failing (a fallback "unknown" member).
4. Emit ``operations.py``: the operation table (method, path, auth, scope, params)
   the handwritten facade dispatches through.

Run via ``scripts/generate.sh``. CI re-runs it and fails on any diff.
"""

from __future__ import annotations

import copy
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec" / "openapi.sdk.json"
OUT = ROOT / "cexy" / "_generated"

HEADER = "# Generated by scripts/generate.py from spec/openapi.sdk.json. DO NOT EDIT.\n"


def preprocess(spec: dict) -> dict:
    spec = copy.deepcopy(spec)
    schemas = spec["components"]["schemas"]
    schemas["Amount"] = {
        "type": "string",
        "format": "decimal",
        "description": schemas["Amount"].get("description", ""),
    }
    for schema in schemas.values():
        for name, prop in schema.get("properties", {}).items():
            if name.endswith("_percent") and prop.get("type") == "string":
                prop["format"] = "decimal"
    return spec


def generate_models(spec: dict) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "spec.json"
        src.write_text(json.dumps(spec))
        out = Path(tmp) / "models.py"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                str(src),
                "--input-file-type",
                "openapi",
                "--output",
                str(out),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.10",
                "--no-use-union-operator",
                "--no-use-standard-collections",
                "--use-subclass-enum",
                "--collapse-root-models",
                "--use-annotated",
                "--field-constraints",
                "--use-double-quotes",
                "--use-schema-description",
                "--disable-timestamp",
                "--enum-field-as-literal",
                "none",
                "--capitalise-enum-members",
                "--extra-fields",
                "allow",
                "--formatters",
                "builtin",
            ],
            check=True,
        )
        text = out.read_text()
    # Tolerant enums: unknown values become pseudo-members instead of validation errors.
    text = re.sub(r"class (\w+)\(str, Enum\):", r"class \1(OpenEnum):", text)
    text = text.replace("from enum import Enum\n", "")
    text = re.sub(r"(from pydantic import [^\n]+\n)", r"\1\nfrom cexy._enum import OpenEnum\n", text, count=1)
    text = re.sub(r"^# generated by datamodel-codegen:\n(#.*\n)*", "", text)
    (OUT / "models.py").write_text(HEADER + text)


def generate_operations(spec: dict) -> None:
    lines = [
        HEADER,
        "from __future__ import annotations\n\n",
        "from typing import NamedTuple, Tuple\n\n\n",
        "class Operation(NamedTuple):\n",
        "    operation_id: str\n    method: str\n    path: str\n",
        '    auth: str  # "none" | "api_key"\n',
        '    scope: str  # "-" | "read" | "trade"\n',
        "    path_params: Tuple[str, ...]\n    query_params: Tuple[str, ...]\n",
        "    idempotency_header: bool\n\n\n",
        "OPERATIONS = {\n",
    ]
    for path, ops in sorted(spec["paths"].items()):
        for method, op in sorted(ops.items()):
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            params = op.get("parameters", [])
            pp = tuple(p["name"] for p in params if p["in"] == "path")
            qp = tuple(p["name"] for p in params if p["in"] == "query")
            idem = any(p["in"] == "header" and p["name"] == "Idempotency-Key" for p in params)
            auth = "api_key" if op.get("security") else "none"
            scope = op.get("x-required-scope", "-")
            lines.append(
                f"    {op['operationId']!r}: Operation({op['operationId']!r}, {method.upper()!r}, "
                f"{path!r}, {auth!r}, {scope!r}, {pp!r}, {qp!r}, {idem!r}),\n"
            )
    lines.append("}\n")
    (OUT / "operations.py").write_text("".join(lines).replace("'", '"'))


def main() -> int:
    spec = json.loads(SPEC.read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "__init__.py").write_text(HEADER + '"""Generated models and operation table."""\n')
    pre = preprocess(spec)
    generate_models(pre)
    generate_operations(spec)
    ruff = [sys.executable, "-m", "ruff"]
    subprocess.run([*ruff, "check", "--fix", "--quiet", "--select", "I,F401", str(OUT)], check=True)
    subprocess.run([*ruff, "format", "--quiet", str(OUT)], check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
