#!/usr/bin/env python3
"""Regenerate cexy/_generated/ from spec/openapi.sdk.json.

Steps:
1. Pre-process the spec: every decimal string (the ``Amount`` schema and string
   ``*_percent`` fields) becomes ``format: decimal`` so the generator emits ``Decimal``.
2. Run datamodel-code-generator (pinned in pyproject ``[dev]``) into ``models.py``.
3. Post-process: response enums inherit ``cexy._enum.OpenEnum`` so unknown values
   parse instead of failing (a fallback "unknown" member).
4. Emit ``operations.py``: the operation table (method, path, auth, scope, params)
   the handwritten facade dispatches through.

Run via ``scripts/generate.sh``. CI re-runs it and fails on any diff.
"""

from __future__ import annotations

import copy
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec" / "openapi.sdk.json"
OUT = ROOT / "cexy" / "_generated"

HEADER = "# Generated by scripts/generate.py from spec/openapi.sdk.json. DO NOT EDIT.\n"


def preprocess(spec: dict) -> dict:
    spec = copy.deepcopy(spec)
    schemas = spec["components"]["schemas"]
    schemas["Amount"] = {
        "type": "string",
        "format": "decimal",
        "description": schemas["Amount"].get("description", ""),
    }
    for schema in schemas.values():
        for name, prop in schema.get("properties", {}).items():
            if name.endswith("_percent") and prop.get("type") == "string":
                prop["format"] = "decimal"
    # Id schemas (OrderId, UserId, ...) are plain strings in the SDK: no client-side format
    # check, so a future id format never breaks decoding (CexyQA, 2026-09-28).
    ID_ALIASES.clear()
    for name, schema in schemas.items():
        if name.endswith("Id") and schema.get("type") == "string":
            for key in ("pattern", "minLength", "maxLength"):
                schema.pop(key, None)
            ID_ALIASES.append(name)
    hoist_ledger_reference(schemas)
    return spec


def _pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


LEDGER_VARIANTS: dict[str, tuple[str, tuple[str, ...]]] = {}  # tag -> (class name, required keys)
ID_ALIASES: list[str] = []  # id schemas, emitted as `OrderId = str` (the generator inlines them)


def hoist_ledger_reference(schemas: dict) -> None:
    """Name each LedgerReference variant after its `type` tag (LedgerReferenceDeposit, ...) and
    drop the union itself: LedgerEntryResponse.reference is typed by the tolerant
    ``LedgerReference`` alias that ``postprocess`` writes (unknown tags decode, never raise)."""
    union = schemas.pop("LedgerReference", None)
    if union is None:
        return
    LEDGER_VARIANTS.clear()
    for variant in union["oneOf"]:
        tag = variant["properties"]["type"]["enum"][0]
        name = f"LedgerReference{_pascal(tag)}"
        variant = copy.deepcopy(variant)
        variant["properties"]["type"] = {"type": "string", "const": tag}
        schemas[name] = variant
        LEDGER_VARIANTS[tag] = (name, tuple(variant.get("required", [])))
    entry = schemas["LedgerEntryResponse"]["properties"]
    entry["reference"] = {"description": union.get("description", "What caused the entry.")}


def ledger_reference_block() -> str:
    """The tolerant union: a known `type` whose data validates as that variant decodes to it;
    anything else (a newer `type`, a missing key, a field of the wrong type, not an object) to
    LedgerReferenceUnknown. Decoding never raises (CexyQA)."""
    tags = ",\n".join(f'    "{tag}": {name}' for tag, (name, _) in sorted(LEDGER_VARIANTS.items()))
    members = "".join(
        f'        Annotated[{name}, Tag("{tag}")],\n' for tag, (name, _) in sorted(LEDGER_VARIANTS.items())
    )
    return f'''class LedgerReferenceUnknown(BaseModel):
    """A cause this SDK version does not know (a newer `type`, or an unexpected shape). Every
    field the server sent is kept; `raw` holds a value that was not an object."""

    model_config = ConfigDict(
        extra="allow",
    )
    type: Optional[Any] = None
    raw: Optional[Any] = None

    @model_validator(mode="before")
    @classmethod
    def _wrap(cls, value: Any) -> Any:
        return value if isinstance(value, dict) else {{"raw": value}}


# The variant each known `type` decodes to.
_LEDGER_REFERENCE_VARIANTS: Dict[str, Type[BaseModel]] = {{
{tags},
}}


def _ledger_reference_tag(value: Any) -> str:
    """Pick the variant. A known `type` is chosen only if its data validates as that variant
    (required keys present, fields of the right types); otherwise "unknown", so that a malformed
    reference is kept as LedgerReferenceUnknown instead of failing the whole entry."""
    if isinstance(value, BaseModel):
        if isinstance(value, LedgerReferenceUnknown):
            return "unknown"
        tag = getattr(value, "type", None)
        return tag if isinstance(tag, str) and tag in _LEDGER_REFERENCE_VARIANTS else "unknown"
    if isinstance(value, dict):
        tag = value.get("type")
        variant = _LEDGER_REFERENCE_VARIANTS.get(tag) if isinstance(tag, str) else None
        if variant is not None:
            try:
                variant.model_validate(value)
            except ValidationError:
                return "unknown"
            return tag  # type: ignore[return-value]
    return "unknown"


LedgerReference = Annotated[
    Union[
{members}        Annotated[LedgerReferenceUnknown, Tag("unknown")],
    ],
    Discriminator(_ledger_reference_tag),
]
"""What caused a ledger entry, told apart by `type`. Unknown or malformed causes decode to
LedgerReferenceUnknown instead of failing."""


'''


def generate_models(spec: dict) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "spec.json"
        src.write_text(json.dumps(spec))
        out = Path(tmp) / "models.py"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                str(src),
                "--input-file-type",
                "openapi",
                "--output",
                str(out),
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.10",
                "--no-use-union-operator",
                "--no-use-standard-collections",
                "--use-subclass-enum",
                "--collapse-root-models",
                "--use-annotated",
                "--field-constraints",
                "--use-double-quotes",
                "--use-schema-description",
                "--disable-timestamp",
                "--enum-field-as-literal",
                "none",
                "--capitalise-enum-members",
                "--extra-fields",
                "allow",
                "--formatters",
                "builtin",
            ],
            check=True,
        )
        text = out.read_text()
    # Tolerant enums: unknown values become pseudo-members instead of validation errors.
    text = re.sub(r"class (\w+)\(str, Enum\):", r"class \1(OpenEnum):", text)
    text = text.replace("from enum import Enum\n", "")
    text = re.sub(r"(from pydantic import [^\n]+\n)", r"\1\nfrom cexy._enum import OpenEnum\n", text, count=1)
    text = re.sub(r"^# generated by datamodel-codegen:\n(#.*\n)*", "", text)
    if ID_ALIASES:
        text = (
            text.rstrip("\n")
            + "\n\n\n# Ids are plain strings: the SDK does not check their format.\n"
            + "".join(f"{name} = str\n" for name in sorted(ID_ALIASES))
        )
    if LEDGER_VARIANTS:
        text = postprocess_ledger_reference(text)
    (OUT / "models.py").write_text(HEADER + text)


def postprocess_ledger_reference(text: str) -> str:
    if "class LedgerEntryResponse(BaseModel):" not in text:
        raise SystemExit("generate.py: LedgerEntryResponse not found in the generated models")
    # The alias names the variant classes, so it goes after every class; models that use it
    # (LedgerEntryResponse and anything containing it) are completed by the rebuild below.
    text = (
        text.rstrip("\n")
        + "\n\n\n"
        + ledger_reference_block()
        + (
            "for _model in list(globals().values()):\n"
            "    if isinstance(_model, type) and issubclass(_model, BaseModel) and _model is not BaseModel \\\n"
            "            and not _model.__pydantic_complete__:\n"
            "        _model.model_rebuild()\n"
        )
    )
    new, n = re.subn(r"(\n    reference: Annotated\[\s*)Any,", r"\1LedgerReference,", text, count=1)
    if n != 1:
        raise SystemExit("generate.py: LedgerEntryResponse.reference field not found")
    text = new
    # Imports the block needs (ruff drops the unused ones afterwards).
    text = _add_imports(text, "typing", {"Annotated", "Any", "Dict", "Optional", "Type", "Union"})
    return _add_imports(
        text, "pydantic", {"BaseModel", "ConfigDict", "Discriminator", "Tag", "ValidationError", "model_validator"}
    )


def _add_imports(text: str, module: str, names: set) -> str:
    def merge(m: re.Match) -> str:
        return f"from {module} import " + ", ".join(sorted(set(m.group(1).split(", ")) | names)) + "\n"

    return re.sub(rf"from {module} import ([^\n]+)\n", merge, text, count=1)


def generate_operations(spec: dict) -> None:
    lines = [
        HEADER,
        "from __future__ import annotations\n\n",
        "from typing import NamedTuple, Tuple\n\n\n",
        "class Operation(NamedTuple):\n",
        "    operation_id: str\n    method: str\n    path: str\n",
        '    auth: str  # "none" | "api_key"\n',
        '    scope: str  # "-" | "read" | "trade"\n',
        "    path_params: Tuple[str, ...]\n    query_params: Tuple[str, ...]\n",
        "    idempotency_header: bool\n\n\n",
        "OPERATIONS = {\n",
    ]
    for path, ops in sorted(spec["paths"].items()):
        for method, op in sorted(ops.items()):
            if method not in {"get", "post", "put", "patch", "delete"}:
                continue
            params = op.get("parameters", [])
            pp = tuple(p["name"] for p in params if p["in"] == "path")
            qp = tuple(p["name"] for p in params if p["in"] == "query")
            idem = any(p["in"] == "header" and p["name"] == "Idempotency-Key" for p in params)
            auth = "api_key" if op.get("security") else "none"
            scope = op.get("x-required-scope", "-")
            lines.append(
                f"    {op['operationId']!r}: Operation({op['operationId']!r}, {method.upper()!r}, "
                f"{path!r}, {auth!r}, {scope!r}, {pp!r}, {qp!r}, {idem!r}),\n"
            )
    lines.append("}\n")
    (OUT / "operations.py").write_text("".join(lines).replace("'", '"'))


def main() -> int:
    spec = json.loads(SPEC.read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "__init__.py").write_text(HEADER + '"""Generated models and operation table."""\n')
    pre = preprocess(spec)
    generate_models(pre)
    generate_operations(spec)
    ruff = [sys.executable, "-m", "ruff"]
    subprocess.run([*ruff, "check", "--fix", "--quiet", "--select", "I,F401", str(OUT)], check=True)
    subprocess.run([*ruff, "format", "--quiet", str(OUT)], check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
