#!/usr/bin/env python3
"""Generate cexy/_sync/ from cexy/_async/ (token replacement, like httpcore's unasync).

Run with ``--check`` in CI to fail when the sync code is stale.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "cexy" / "_async"
DST = ROOT / "cexy" / "_sync"

SUBS = [
    # Module docstrings: describe the generated sync module, not the async source.
    (
        r"Async source; the synchronous ``cexy/_sync/(\w+\.py)`` is generated from it by\s+``scripts/unasync\.py``\.",
        r"Synchronous version, generated from ``cexy/_async/\1`` by ``scripts/unasync.py``:"
        r"\nedit that file, not this one.",
    ),
    (r"\(asyncio, ``httpx\.AsyncClient``\)", "(synchronous, ``httpx.Client``)"),
    (r"The async client \(``AsyncClient``\)", "The synchronous client (``Client``)"),
    (r"\bimport asyncio\b", "import time"),
    (r"\basyncio\.sleep\b", "time.sleep"),
    (r"\basync def\b", "def"),
    (r"\basync for\b", "for"),
    (r"\basync with\b", "with"),
    (r"\bawait ", ""),
    (r"for item in page\.items:\n(\s+)yield item", r"yield from page.items"),
    (r"\bAsyncIterator\b", "Iterator"),
    (r"\bhttpx\.AsyncClient\b", "httpx.Client"),
    (r"\bAsyncClient\b", "Client"),
    (r"\bAsyncTransport\b", "SyncTransport"),
    (r"\bAsyncPage\b", "Page"),
    (r"\bAsync([A-Z]\w*)\b", r"\1"),
    (r"\b__aenter__\b", "__enter__"),
    (r"\b__aexit__\b", "__exit__"),
    (r"\baclose\b", "close"),
    (r"\bcexy\._async\b", "cexy._sync"),
    (r"\(asyncio\)", "(synchronous)"),
    (r"``async for item in page\.auto_paging_iter\(\)``", "``for item in page.auto_paging_iter()``"),
    (r"``await page\.next_page\(\)``", "``page.next_page()``"),
    (
        r"``async with Client\(\) as client: \.\.\.`` or call ``client\.close\(\)``",
        "``with Client() as client: ...`` or call ``client.close()``",
    ),
]

BANNER = "# Generated by scripts/unasync.py from cexy/_async/{name}. DO NOT EDIT.\n"


def convert(text: str) -> str:
    for pat, rep in SUBS:
        text = re.sub(pat, rep, text)
    return text


def render(tmp: Path) -> None:
    for src in sorted(SRC.glob("*.py")):
        (tmp / src.name).write_text(BANNER.format(name=src.name) + convert(src.read_text()))
    ruff = [sys.executable, "-m", "ruff"]
    cfg = ["--config", str(ROOT / "pyproject.toml")]
    subprocess.run([*ruff, "check", *cfg, "--fix", "--quiet", "--select", "I,F401", str(tmp)], check=True)
    subprocess.run([*ruff, "format", *cfg, "--quiet", str(tmp)], check=True)


def main() -> int:
    check = "--check" in sys.argv
    DST.mkdir(exist_ok=True)
    stale = []
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)
        render(tmp)
        for out in sorted(tmp.glob("*.py")):
            dst = DST / out.name
            if check:
                if not dst.exists() or dst.read_text() != out.read_text():
                    stale.append(str(dst.relative_to(ROOT)))
            else:
                shutil.copyfile(out, dst)
    if stale:
        print("stale generated sync code (run scripts/generate.sh):", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
